name: Curation Admin Tools

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    name: Run Unit Tests

    defaults:
      run:
        shell: bash
        working-directory: ./

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3.6.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.8.2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run the test suite
        run: npm test
